name: Deployment

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install
          npm run build

      - name: Deploy
        run: |
          # scp -i ${{ secrets.SSH_PUBLIC_KEY }} -r ./build/* ${{ secrets.SSH_KEY }}:/usr/share/nginx/html
          # scp -i <(echo "${{ secrets.SSH_PUBLIC_KEY }}") -r ./build/* ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_SERVER_IP }}:/usr/share/nginx/html
          echo "$SSH_PRIVATE_KEY" > deploy_key.pem
          chmod 600 deploy_key.pem
          scp -i deploy_key.pem -r ./build/* ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_SERVER_IP }}:/usr/share/nginx/html
          rm -f deploy_key.pem
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PUBLIC_KEY }}

