name: Deployment

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install
          npm run build
      
      - name: Debug SSH Key
        run: |
          echo "SSH_SERVER_IP: $SSH_SERVER_IP"
          echo "SSH_PUBLIC_KEY: $SSH_PUBLIC_KEY"

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Copy Code to Azure VM
        run: |
          scp -i ~/.ssh/id_rsa -r ./* tahmid@${{ secrets.SSH_SERVER_IP }}:/var/www/html/

      - name: Deploy
        run: |
          ssh -i ~/.ssh/id_rsa tahmid@${{ secrets.SSH_SERVER_IP }} "cd /var/www/html/ && git pull && npm install && npm run build"
