name: Deployment

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install
          npm run build
      
      - name: Debug SSH Key
        run: |
          echo "SSH_SERVER_IP: $SSH_SERVER_IP"
          echo "SSH_PUBLIC_KEY: $SSH_PUBLIC_KEY"


      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/ssh_key.pub
          chmod 600 ~/.ssh/ssh_key.pub
          ssh-keyscan -H ${{ secrets.SSH_SERVER_IP }} >> ~/.ssh/known_hosts
          mv ~/.ssh/ssh_key.pub ~/.ssh/id_rsa.pub




      - name: Deploy
        run: |
          scp -i ~/.ssh/id_rsa.pub -r ./build/* ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_SERVER_IP }}:/path/to/your/destination
        env:
          SSH_SERVER_IP: ${{ secrets.SSH_SERVER_IP }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}


