name: Deployment

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install
          npm run build

      - name: Deploy
        run: |
          # You can use SSH or any other method to copy the built app to your Azure VM.
          # Example using SSH and SCP:
          scp -i <(echo "$SSH_PRIVATE_KEY") -r ./build/* ssh_key:/usr/share/nginx/html
          rm -f ssh_key
        env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
